# Generated by Django 6.1.1 on 2026-09-27 06:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PinSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pin_length",
                    models.PositiveSmallIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "unlock_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                ("sliding_unlock", models.BooleanField(default=True)),
                ("scope_mode", models.CharField(default="global", max_length=20)),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "lockout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10080),
                        ],
                    ),
                ),
                ("block_weak_pins", models.BooleanField(default=True)),
                ("blocked_pins", models.TextField(blank=True)),
                ("max_age_days", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "PIN settings",
                "verbose_name_plural": "PIN settings",
            },
        ),
        migrations.CreateModel(
            name="PinEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "action",
                    models.CharField(db_index=True, editable=False, max_length=30),
                ),
                (
                    "username",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "actor_username",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                ("scope", models.CharField(blank=True, editable=False, max_length=100)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("detail", models.TextField(blank=True, editable=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PIN event",
                "verbose_name_plural": "PIN events",
                "ordering": ("-time", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="UserPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("pin_hash", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("changed", models.DateTimeField(blank=True, null=True)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_pin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user PIN",
                "verbose_name_plural": "user PINs",
                "ordering": ("user__username",),
            },
        ),
    ]
