# Generated by Django 6.1.1 on 2026-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsettings",
            name="access_mode",
            field=models.CharField(default="all", max_length=20),
        ),
        migrations.AddField(
            model_name="userpin",
            name="access",
            field=models.CharField(default="default", max_length=20),
        ),
    ]
