# Generated by Django 6.1.1 on 2026-09-27 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def upgrade_existing(apps, schema_editor):
    """
    New defaults: PIN use only for allowed users, rotation every 180 days. Users who already have a PIN are
    marked as allowed so nobody loses access.
    """
    PinSettings = apps.get_model('netbox_user_pin', 'PinSettings')
    UserPin = apps.get_model('netbox_user_pin', 'UserPin')
    PinSettings.objects.filter(max_age_days=0).update(max_age_days=180)
    PinSettings.objects.update(access_mode='allowed_only')
    UserPin.objects.exclude(pin_hash='').filter(access='default').update(access='allowed')


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0002_access"),
        ("users", "0016_default_ordering_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsettings",
            name="allowed_email_domains",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="recovery_minutes",
            field=models.PositiveIntegerField(
                default=15,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="require_2fa_admin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="require_2fa_unlock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="self_recovery",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="step_up_minutes",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="warn_days",
            field=models.PositiveIntegerField(
                default=14, validators=[django.core.validators.MaxValueValidator(365)]
            ),
        ),
        migrations.AddField(
            model_name="userpin",
            name="backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userpin",
            name="expiry_warned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpin",
            name="must_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpin",
            name="recovery_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userpin",
            name="recovery_code",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="userpin",
            name="recovery_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpin",
            name="recovery_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpin",
            name="totp_enabled",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpin",
            name="totp_last_step",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userpin",
            name="totp_secret",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pinsettings",
            name="access_mode",
            field=models.CharField(default="allowed_only", max_length=20),
        ),
        migrations.AlterField(
            model_name="pinsettings",
            name="max_age_days",
            field=models.PositiveIntegerField(
                default=180,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3650),
                ],
            ),
        ),
        migrations.CreateModel(
            name="PinDelegate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("can_edit_settings", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.group",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PIN delegate",
                "verbose_name_plural": "PIN delegates",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("group__isnull", True), ("user__isnull", False)),
                            models.Q(("group__isnull", False), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="netbox_user_pin_delegate_user_xor_group",
                    )
                ],
            },
        ),
        migrations.RunPython(upgrade_existing, migrations.RunPython.noop),
    ]
