# Generated by Django 6.1.1 on 2026-09-27 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0003_twofactor_recovery_delegates"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsettings",
            name="reset_valid_hours",
            field=models.PositiveIntegerField(
                default=24,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(336),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpin",
            name="pending_reset",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="userpin",
            name="pending_reset_by",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userpin",
            name="pending_reset_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpin",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpin",
            name="suspended_by",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
