# Generated by Django 6.1.1 on 2026-09-27 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0004_suspend_admin_reset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsettings",
            name="approval_valid_minutes",
            field=models.PositiveIntegerField(
                default=1440,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(10080),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="break_glass",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="four_eyes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="four_eyes_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="four_eyes_delegates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="four_eyes_settings",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpin",
            name="backup_codes_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpin",
            name="email_code_purpose",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                ("payload", models.JSONField(default=dict)),
                ("summary", models.CharField(max_length=500)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("requested_by_name", models.CharField(max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires", models.DateTimeField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("result", models.TextField(blank=True)),
                ("break_glass", models.BooleanField(default=False)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "four-eyes request",
                "verbose_name_plural": "four-eyes requests",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ApprovalVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("approve", models.BooleanField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="netbox_user_pin.approvalrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("time",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "user"),
                        name="netbox_user_pin_one_vote_per_user",
                    )
                ],
            },
        ),
    ]
