# Generated by Django 6.1.1 on 2026-09-27 15:49

import django.core.validators
from django.db import migrations, models


def move_domains(apps, schema_editor):
    """Domains from the old text field become allowed domains that still have to be verified."""
    PinSettings = apps.get_model('netbox_user_pin', 'PinSettings')
    AllowedDomain = apps.get_model('netbox_user_pin', 'AllowedDomain')
    for settings in PinSettings.objects.all():
        for line in (settings.allowed_email_domains or '').replace(',', '\n').splitlines():
            domain = line.strip().lower().lstrip('@').rstrip('.')
            if domain:
                AllowedDomain.objects.get_or_create(domain=domain, defaults={'created_by': 'migration'})


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0005_four_eyes_backup_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("verified", models.DateTimeField(blank=True, null=True)),
                ("verified_by", models.CharField(blank=True, max_length=150)),
                ("verified_email", models.CharField(blank=True, max_length=254)),
                ("code", models.CharField(blank=True, max_length=128)),
                ("code_email", models.CharField(blank=True, max_length=254)),
                ("code_expires", models.DateTimeField(blank=True, null=True)),
                ("code_attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "allowed e-mail domain",
                "verbose_name_plural": "allowed e-mail domains",
                "ordering": ("domain",),
            },
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="mail_from_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="mail_from_name",
            field=models.CharField(blank=True, default="NetBox PIN", max_length=100),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_auth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_auto_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_password",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_port",
            field=models.PositiveIntegerField(
                default=25,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_security",
            field=models.CharField(default="none", max_length=10),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_server",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_timeout",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pinsettings",
            name="smtp_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(move_domains, migrations.RunPython.noop),
    ]
