# Generated by Django 6.1.1 on 2026-09-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0006_smtp_allowed_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsettings",
            name="language",
            field=models.CharField(default="en", max_length=5),
        ),
    ]
