# Generated by Django 6.1.1 on 2026-09-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0007_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsettings",
            name="require_2fa_settings",
            field=models.BooleanField(default=False),
        ),
    ]
