# Generated by Django 6.1.1 on 2026-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_user_pin", "0008_require_2fa_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinsettings",
            name="show_full_names",
            field=models.BooleanField(default=True),
        ),
    ]
